# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#El siguiente codigo sirve para entrenar un modelo que clasifica
#datos usando el algoritmo K-Nearest Neighbors
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
#Se importan las librerias necesarias para el proceso

# 1. Crear un dataset simple
X, y = make_classification(
    n_samples=200,
    n_features=2,
    n_classes=2,
    n_redundant=0,
    n_informative=2,
    random_state=42
)

# 2. Separar datos: entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# 3. Crear el modelo KNN
modelo = KNeighborsClassifier(n_neighbors=3)

# 4. Entrenar el modelo
modelo.fit(X_train, y_train)

# 5. Predecir en los datos de prueba
y_pred = modelo.predict(X_test)

# 6. Medir precisión
accuracy = accuracy_score(y_test, y_pred)

print("Precisión del modelo:", accuracy)
